### ISSUE TITLE
How long does it take to convert MRCP phantom in obj format to .ele and .node format?

### ISSUE THREAD

**Issue by zzj00** [haeginh/POLY2TET#3]
I tried to convert MRCP to .ele, but it took about 20h and a lot of memory to complete, and the programme didn't report an error!

**Comment by haeginh** [comment]
Hi,

When I used my intel i7 core (2017), it took less than 10 minutes. It was
also the same in my laptops.

Best regards,
Haegin

2023년 9월 19일 (화) 오후 6:20, zzj00 ***@***.***>님이 작성:

**Comment by zzj00** [comment]
Thank you very much for your reply, your code is very helpful. 
My phantom is from ICRP145 and unmodified, the conversion using POLY2TET is not successful, it keeps repeating the following.  Is it a mesh phantom problem or which parameters need to be modified？

Opening MRCP_AM.smesh.
Opening MRCP_AM.node.
Delaunizing vertices...
Warning:  Point #578183 is coincident with #577572. Ignored!
Warning:  Point #570620 is coincident with #570009. Ignored!
Delaunay seconds:  17.8746
Creating surface mesh ...
Found two nearly self-intersecting facets.
  1st: [548623, 548838, 548651] #5800
  2nd: [548623, 548838, 548417] #5800
The dihedral angle between them is 0.0877662 degree.
Hint:  You may use -p/# to decrease the dihedral angle  tolerance 0.1 (degree).
Opening MRCP_AM.smesh.
Opening MRCP_AM.node.
Delaunizing vertices...
Warning:  Point #577572 is coincident with #578183. Ignored!
Warning:  Point #570009 is coincident with #570620. Ignored!
Delaunay seconds:  17.9311
Creating surface mesh ...
Found two nearly self-intersecting facets.
  1st: [548623, 548838, 548651] #5800
  2nd: [548623, 548838, 548417] #5800
The dihedral angle between them is 0.0877662 degree.
Hint:  You may use -p/# to decrease the dihedral angle  tolerance 0.1 (degree).
Opening MRCP_AM.smesh.
Opening MRCP_AM.node.
Delaunizing vertices...
Warning:  Point #578183 is coincident with #577572. Ignored!
Warning:  Point #570009 is coincident with #570620. Ignored!
Delaunay seconds:  17.9007

**Comment by haeginh** [comment]
I see. Can you please run the code by including -s option?
The -s option sometimes solve this issue.

**Comment by zzj00** [comment]
Thank you very much for your help. I have successfully solved the problem according to your advice.



---- Replied Message ----
| From | Haegin ***@***.***> |
| Date | 09/21/2023 17:49 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [haeginh/POLY2TET] How long does it take to convert MRCP phantom in obj format to .ele and .node format? (Issue #3) |

I see. Can you please run the code by including -s option?
The -s option sometimes solve this issue.
